Administrador  cria conta
TreinaDev/CartoesEPagamentosTD10 pull request #11
Opened 2023-06-07 18:59 UTC by LuizQuintanilha

Administrador é capaz de criar uma conta informando email, senha, cpf, e nome.
Email deve possuir o domínio @punti.com
Cpf deve ser único e válido
Configuração do i18n pro devise
Administrador é capaz de fazer login e se deslogar

2023-06-09 13:30 UTC, joaorsalmeida requested changes
Deixei alguns comentários com ajustes que podem ser feitos...

2023-06-09 13:30 UTC, joaorsalmeida commented on db/seeds.rb
> +Admin.new(
Só `.new`? O seeds deveria popular o banco de dados então faltou um `save` ou mudar para `create`. Também recomendo sempre usar os métodos com '!' para garantir que foram executados com sucesso.

2023-06-09 13:30 UTC, joaorsalmeida commented on spec/models/payment_spec.rb
> +# RSpec.describe Payment, type: :model do
Não é muito legal deixar esses comentários, era melhor deixar o bloco de código vazio ou remover de vez o arquivo.

2023-06-09 13:30 UTC, joaorsalmeida commented on spec/system/admin/admin_register_spec.rb
> +      # Arrange
Não precisamos mais desses comentários. Usamos no começo como aprendizado. Agora podemos só separar os 'blocos' com uma linha vazia.

2023-06-09 15:26 UTC, LuizQuintanilha commented on app/views/devise/registrations/new.html.erb
> +    <%= f.label :name, 'Nome Completo' %><br />
Correto João. Esqueci de apagar essas strings depois que traduzi elas! Mas já corrigi e vou subir um novo push.

2023-06-09 15:42 UTC, LuizQuintanilha commented on spec/models/payment_spec.rb
> +# RSpec.describe Payment, type: :model do
Foi retirado os comentários das linhas e mantido o bloco.

2023-06-09 15:42 UTC, LuizQuintanilha commented on config/locales/devise.en.yml
> -      inactive: "Your account is not activated yet."
Foi feita a remoção dos arquivos en.yml.

2023-06-09 15:50 UTC, LuizQuintanilha commented on app/views/devise/sessions/new.html.erb
> +    <%= f.label :password, 'Senha' %><br />
A correção foi realizada.

2023-06-09 16:18 UTC, LuizQuintanilha reviewed
Foram apagados os comentários nos arquivos de testes, excluído os arquivos en.yml, e correção da seeds.

2023-06-12 12:53 UTC, gabdemiranda commented on spec/models/admin_spec.rb
> +        expect(result).to eq false
Uma coisa que poderia ser interessante é adicionar uma expectativa que deixa claro o erro do atributo. Entendo que existe a validação, mas talvez outro atributo estivesse falhando (como por exemplo, o email por algum motivo) e o teste estaria retornando um "falso positivo". Podemos fazer isso com uma expectativa que checa se existe o erro no atributo do objeto, como: `expect(luiz.errors.full_messages).to include('mensagem de erro esperada')`. tem outras formas também mas essa é uma das opções pra deixar mais completinho =)

2023-06-12 14:37 UTC, gabdemiranda commented
Se possível, nos testes de system, seria mais interessante não separar em pastas por models, talvez apenas separar em tipos de usuário/acesso ou funcionalidade, ou até deixar esses testes de navegação na pasta system direto e a descrição ajudar a indentificar, como esses testes acabam envolvendo diferentes modelos e funcionalidades combinadas.

2023-06-12 15:36 UTC, LuizQuintanilha commented on spec/models/admin_spec.rb
> +        expect(result).to eq false
Obrigado pelo conselho Gabriel. Vou implementar e fazer novo commit.

2023-06-12 20:56 UTC, merged