Api deactivate card
TreinaDev/CartoesEPagamentosTD10 pull request #15
Opened 2023-06-09 14:32 UTC by ThiagoDFi

Criação de uma endpoint para a inativação de um cartão.

Deve ser enviado o ID do cartão do funcionário para que possa ser realizado a ação.

É realizado a atualização do status do cartão de "Active" para "inactive".

close #8

2023-06-12 15:05 UTC, gabdemiranda requested changes

2023-06-12 15:05 UTC, gabdemiranda commented on spec/models/card_spec.rb
> +      expect(result).to eq false
Como dito anteriormente, é necessário adicionar mais expectativas que deixem claro qual atributo está falhando, possivelmente através da checagem da mensagem de erro no objeto, para garantir que o teste não seja um "falso positivo"

2023-06-12 15:05 UTC, gabdemiranda commented on spec/requests/APIs/deactivate_card_api_spec.rb
> +end
O que aconteceria se apenas um dos atributos estivesse correto? por exemplo, passar o id do company_card, mas passar um CPF vazio ou inválido? e vice versa? talvez seja interessante testar essas possibilidades.

2023-06-13 12:53 UTC, rafaeldejesusl commented on spec/models/card_spec.rb
> +      expect(result).to eq false
Ok, vou adicionar essa checagem.

2023-06-13 13:03 UTC, rafaeldejesusl commented on spec/requests/APIs/deactivate_card_api_spec.rb
> +end
Eu não sei se compreendi erroneamente sua sugestão, mas essa rota recebe apenas o id do cartão como parâmetro. O cpf e company_card foi utilizado apenas para criar o cartão que será desativado. Dessa forma, não vejo como será feito esse teste citado, pois a requisição recebe apenas um id do cartão cuja verificação já foi feita no primeiro teste. Caso considere que ainda está errado, poderia explicar melhor como seria feito esse teste?

2023-06-13 13:34 UTC, gabdemiranda commented on spec/requests/APIs/deactivate_card_api_spec.rb
> +end
Perdão, me confundi lendo o teste mesmo. A requisição só passa o ID

2023-06-13 15:24 UTC, gabdemiranda commented
Como dito no PR de criação, vi que existe alguns commits nessa branch que não pertencem a ela, vem da outra branch de criação aparentemente. Gostaria de reforçar que não devemos dar pull de uma branch que não seja a main em outra branch para atualizar ou iniciar a "codar", o ideal é esperar que o código seja mergeado na main para dar pull dela, ou adicionar as partes do código necessárias para o desenvolvimento da sua branch manualmente e depois resolver os possíveis conflitos para não bagunçar o histórico de commits com coisas que não deveriam ser consideradas nessas alterações. Como eu disse, acho que se mergeamos o PR de criação na main e depois dar um pull da main nessa branch, conseguiremos remover esses commits clonados que não pertencem a esse PR, por enquanto vou deixar pendente de aprovação até a gente conseguir resolver essa questão do histórico, depois eu aprovo e seguimos com o merge dessa, ok?

2023-06-13 17:19 UTC, rafaeldejesusl commented
Blz, vou iniciar a partir da main agora. Já dei o merge na outra branch e atualizei essa para resolver os conflitos.

2023-06-13 17:20 UTC, gabdemiranda approved these changes

2023-06-13 17:21 UTC, merged