Tela de disponibilização de cartões para empresas
TreinaDev/CartoesEPagamentosTD10 pull request #16
Opened 2023-06-10 18:11 UTC by montteiropedro

- Criação de uma tela de listagem das empresas obtidas através de uma API.
- Criação de uma tela para vincular / disponibilizar / indisponibilizar tipos de cartões para uma empresa.

close #5

2023-06-12 16:00 UTC, gabdemiranda requested changes
Fiz alguns comentários e gostaria de reforçar:
- precisamos separar os testes de requisição em uma nova pasta e testar todas as expectativas que podem ser retornadas nas requisições
- não é obrigatório mas é indicado reorganizar os testes da pasta system para evitar separar em "modelos", já que testes de sistema verificam o comportamento do conjunto ao navegar
- tirar prints e imagens para colocar na descrição do PR explicando as diversas possiblidades de feedback visual que os usuários vão se deparar com as novas modificações e garantir testes para todas essas possibiliidades.

2023-06-13 20:27 UTC, Degorous commented on app/models/company.rb
> +  # TODO: Pedir API para o time de empresas
Foram retirados os comentários.

2023-06-13 20:31 UTC, Degorous commented on app/views/companies/index.html.erb
> +<h1 class='my-4 d-flex justify-content-between align-items-center fs-2'><%= t('.provide_card_types') %></h1>
Foram adicionadas fotos na descrição.

2023-06-13 20:33 UTC, Degorous commented on spec/models/company_spec.rb
> +end
Os testes foram reorganizados, foi criado pasta "requests" para validar os testes de requisição.

2023-06-13 20:34 UTC, Degorous commented on spec/system/company_card_types/admin_change_company_card_type_status_spec.rb
> +end
Removemos o teste da pasta 'company_card_types' e colocamos na pasta 'system'.

2023-06-13 22:19 UTC, Degorous commented on spec/system/company_card_types/admin_create_company_card_type_spec.rb
> +end
Conversamos com algumas pessoas do time e entendemos que essa mensagem será para uma futura implementação, por isso ela não fazia muito sentido estar lá agora e foi removida do código.

2023-06-14 13:11 UTC, gabdemiranda approved these changes
Deixei um pequeno comentário de sugestão de nome mas já vou deixar aprovado para mergear, tudo ok!

2023-06-14 13:32 UTC, Degorous commented on app/controllers/company_card_types_controller.rb
> +  def fetch_company_card_type
Alterado.

2023-06-14 13:40 UTC, merged