Criação da endpoint para receber pedido de pagamentos
TreinaDev/CartoesEPagamentosTD10 pull request #25
Opened 2023-06-14 21:48 UTC by ThiagoDFi

Criamos uma endpoint onde deve ser enviado os seguintes dados:

- Número do pedido
- CPF
- Valor total
- Valor do desconto
- Valor final
- Status
- Código do pedido
- Número do cartão
- Data de pagamento

E retornamos o status sempre como "Pendente", e um Código alfanumérico de 10 caracteres se todos os dados forem enviados corretamente, e retornamos erro 400 caso não tenha conteúdo e 412 caso esteja faltando algum parâmetro obrigatório.

rota para a endpoint localhost:3000/api/v1/payments

close #19

2023-06-15 13:17 UTC, gabdemiranda requested changes

2023-06-15 19:27 UTC, ThiagoDFi commented on spec/factories/payments.rb
>      code { 'MyString' }
Realizamos a remoção do campo code dentro do FactoryBot.

2023-06-15 19:27 UTC, ThiagoDFi commented on spec/models/payment_spec.rb
> +      result = FactoryBot.create(:payment)
Realizamos a remoção do campo code dentro do FactoryBot.

2023-06-15 20:41 UTC, rafaeldejesusl commented on spec/models/payment_spec.rb
> +      expect(result).to eq false
Gostei da quantidade de cenários testados, mas imagino que seria mais adequado adicionar uma verificação para validar se o erro específico está retornando, semelhante aos outros testes de models.

2023-06-15 22:36 UTC, Degorous commented on spec/models/payment_spec.rb
> +      expect(result).to eq false
Alteramos os testes unitários para verificar se o erro realmente acontece.

2023-06-16 00:04 UTC, rafaeldejesusl approved these changes

2023-06-16 12:27 UTC, GA9BR1 approved these changes
Tudo ok Thiago !

2023-06-16 13:40 UTC, montteiropedro approved these changes
Dei uma olhada aqui, e está tudo ok por mim também.

2023-06-16 17:08 UTC, gabdemiranda approved these changes

2023-06-16 17:52 UTC, merged