Criação de regras de cashback e exibição
TreinaDev/CartoesEPagamentosTD10 pull request #26
Opened 2023-06-15 00:13 UTC by GA9BR1

close #17

-  Adilção página de cadastro de regra de cashback 
![Screenshot_780](https://github.com/TreinaDev/CartoesEPagamentosTD10/assets/91296759/188da354-90d2-4eab-b253-49138a28913b)
- Adição da página de listagem de regras de cashback
![Screenshot_781](https://github.com/TreinaDev/CartoesEPagamentosTD10/assets/91296759/51a56a06-4030-43ef-8710-aa33c4c30153)
- Adição de I18n em páginas que faltavam
- Refatoração de testes, para funcionar com a autenticação e autorização.
- Estilizações iniciais em todas as páginas
![Screenshot_777](https://github.com/TreinaDev/CartoesEPagamentosTD10/assets/91296759/c70a25da-57b7-4040-99ed-2d615e605102)
![Screenshot_776](https://github.com/TreinaDev/CartoesEPagamentosTD10/assets/91296759/05224736-9599-4a09-a378-aedfea579b20)
![Screenshot_779](https://github.com/TreinaDev/CartoesEPagamentosTD10/assets/91296759/c092734f-0a1e-4d6e-bd54-f34995608699)
![Screenshot_778](https://github.com/TreinaDev/CartoesEPagamentosTD10/assets/91296759/52879f67-add7-463e-b1d3-b13ab79d83e4)

2023-06-15 13:39 UTC, gabdemiranda requested changes
Em geral parece tudo ok, mas preciso chamar a atenção para o tamanho desse PR, são 49 modificações de coisas que fogem da issue, existe readequação/refatoração de tradução (que poderia ser uma issue separada e um PR separado), existe refatoração visual das telas da plataforma (que poderia ser uma nova issue em um outro PR). Dessa forma a revisão fica mais fácil, as tarefas ficam mais divididas e organizadas e evita que um problema em um dos aspectos de PR trave todas as outras mudanças até se resolver tudo. O ideal era se limitar na criação de regras de cashback apenas nesse PR.

2023-06-15 13:39 UTC, gabdemiranda commented on spec/system/admin_register_cashback_rule_spec.rb
Não seria interessante existir um teste confirmando a validação e as mensagens de erro que aparecem caso tente "preencher" esses campos em branco?

2023-06-15 14:08 UTC, GA9BR1 commented on spec/system/admin_register_cashback_rule_spec.rb
Seria sim Gabriel, iremos implementar. Sobre o tamanho do PR iremos prestar mais atenção no próximo.

2023-06-16 13:08 UTC, ThiagoDFi commented
@GA9BR1 Man quanto ao PR em si está tudo OK, mas olhando para tela do Log in acredito que a aplicação de estilo tenha afetado essa tela.

Pra mim ela ficou dessa maneira, com um botão no meio da tela para manter logado.
![image](https://github.com/TreinaDev/CartoesEPagamentosTD10/assets/57951485/36453551-016c-4322-8e37-430ef628c5ce)

2023-06-16 13:15 UTC, ThiagoDFi requested changes

2023-06-16 13:15 UTC, ThiagoDFi commented on app/assets/stylesheets/application.bootstrap.scss
> +@import './custom/global.scss';
@GA9BR1 Man quanto ao PR em si está tudo OK, mas olhando para tela do Log in acredito que a aplicação de estilo tenha afetado essa tela.

Pra mim ela ficou dessa maneira, com um botão no meio da tela para manter logado.

![image](https://github.com/TreinaDev/CartoesEPagamentosTD10/assets/57951485/2139cb7f-4109-477d-a080-c37dc0636a15)

2023-06-16 13:53 UTC, GA9BR1 commented on app/assets/stylesheets/application.bootstrap.scss
> +@import './custom/global.scss';
Vamos arrumar aqui

2023-06-16 17:02 UTC, ThiagoDFi approved these changes

2023-06-16 18:12 UTC, LuizQuintanilha commented
Tudo ok

2023-06-16 18:20 UTC, LuizQuintanilha approved these changes

2023-06-16 19:37 UTC, GA9BR1 reviewed
Feito

2023-06-16 19:56 UTC, gabdemiranda approved these changes

2023-06-16 20:01 UTC, merged