API de upgrade do cartão
TreinaDev/CartoesEPagamentosTD10 pull request #27
Opened 2023-06-15 19:58 UTC by rafaeldejesusl

Criação do endpoint para upgrade do tipo de cartão.

Receberá o CPF e o id do tipo de cartão da empresa no corpo da requisição, verificando a existência de um cartão antigo válido e do mesmo CPF, alterando seu status para bloqueado e criando um novo cartão que será retornado.

2023-06-16 15:26 UTC, noliv197 requested changes

2023-06-16 15:26 UTC, noliv197 commented on spec/requests/APIs/upgrade_card_api_spec.rb
Faltou o cenário de quando a requisição é feita com o tipo de cartão que o funcionário já tem. No estado atual ele bloqueia e gera um novo sem necessidade

2023-06-16 17:08 UTC, LuizQuintanilha commented
fora o comentário da Natália, acho que ta tudo certo!

2023-06-16 18:45 UTC, rafaeldejesusl commented on spec/requests/APIs/upgrade_card_api_spec.rb
Blz, adicionei essa verificação tbm.

2023-06-16 19:56 UTC, ThiagoDFi commented
Tudo certo man!

2023-06-16 21:39 UTC, noliv197 approved these changes

2023-06-19 13:10 UTC, gabdemiranda approved these changes
Apenas lembrando, vi que algumas pessoas como @LuizQuintanilha e @ThiagoDFi comentaram que aprovavam o PR, mas na prática só temos uma aprovação, e como combinado, só iremos revisar após duas aprovações do time. Aprovei esse comentando apenas para chamar a atenção e lembrar que além de comentar que aprova, é necessário fazer um review aprovando o PR.

2023-06-19 14:43 UTC, rafaeldejesusl commented on app/controllers/api/v1/cards_controller.rb
> +  def prepare_new_card
Blz, vou alterá-lo.

2023-06-19 14:55 UTC, rafaeldejesusl commented
> Apenas lembrando, vi que algumas pessoas como @LuizQuintanilha e @ThiagoDFi comentaram que aprovavam o PR, mas na prática só temos uma aprovação, e como combinado, só iremos revisar após duas aprovações do time. Aprovei esse comentando apenas para chamar a atenção e lembrar que além de comentar que aprova, é necessário fazer um review aprovando o PR.

A gente tentou falar contigo na sexta pois a aprovação dos alunos estava permitindo o merge, mas o Otávio conversou conosco e pra evitar o problema de alguém fazer merge antes de alguém da CampusCode validar, seria legar usar os comentários ao invés da aprovação da review.

2023-06-19 19:59 UTC, montteiropedro approved these changes

2023-06-19 20:00 UTC, merged