Testes de model e sistema
TreinaDev/CartoesEPagamentosTD10 pull request #53
Opened 2023-06-28 12:43 UTC by LuizQuintanilha

Garantia de 100% de cobertura dos testes

2023-06-28 12:52 UTC, ThiagoDFi requested changes
Pessoal, acho que ficou faltando garantir que o numero do cartão é único.

2023-06-28 14:27 UTC, joaorsalmeida commented on Gemfile
> +gem 'actionpack', '~> 7.0.5.1'
Não faz muito sentindo adicionar esta gem aqui pois ela é uma dependência do `Rails`.  O certo seria atualizar o Rails para o 7.0.5.1.

2023-06-28 18:06 UTC, LuizQuintanilha commented on Gemfile
> +gem 'actionpack', '~> 7.0.5.1'
OK... vamos fazer a alteração!

2023-06-28 18:47 UTC, joaorsalmeida requested changes

2023-06-28 18:47 UTC, joaorsalmeida commented on spec/system/admin_visit_error_page_spec.rb
> +    allow_any_instance_of(HomeController).to receive(:index).and_raise(ActiveRecord::RecordNotFound)
Não gosto muito dessa abordagem pois o uso de `any_instance_of` não é muito recomendado. Seria melhor forçar um erro com uma classe/método que são acionados dentro do contexto da execução da action.

2023-06-28 18:47 UTC, joaorsalmeida commented on spec/system/admin_visit_error_page_spec.rb
> +    allow_any_instance_of(HomeController).to receive(:index).and_raise(Faraday::ConnectionFailed)
O mesmo de cima vale aqui...

2023-06-28 20:11 UTC, rafaeldejesusl commented on spec/system/admin_visit_error_page_spec.rb
> +    allow_any_instance_of(HomeController).to receive(:index).and_raise(ActiveRecord::RecordNotFound)
Ok, fizemos a alteração.

2023-06-28 20:14 UTC, rafaeldejesusl commented on spec/system/admin_visit_error_page_spec.rb
> +    allow_any_instance_of(HomeController).to receive(:index).and_raise(Faraday::ConnectionFailed)
A gente percebeu que essa página não era exibida em nenhum cenário de contexto real da aplicação, então resolvemos retirar o rescue da página. Os erros no Faraday já são tratados num erro específico criado pela gente.

2023-06-29 18:15 UTC, ThiagoDFi approved these changes

2023-06-30 12:39 UTC, merged